### ISSUE TITLE
Some general help surrounding NixOS

### ISSUE THREAD

**Issue by daedaevibin** [JaKooLit/Ja-ZaneyOS#1]
Is NixOS still functional?

I can't seem to run the installer in any form or way. It just shows the step 1 thing, the logo thing for loading if I'm lucky, and then absolutely nothing but a black screen (a cursor at a standstill if lucky) and shuts off perfectly fine.

Could it be because I was using Ventoy? I'm about to write it fully to my USB to test that.

I'm seriously confused. After waiting 5+ minutes still no feedback

I'm fully new to NixOS and thought you may be able to assist even if a little

**Comment by JaKooLit** [comment]
![image](https://github.com/user-attachments/assets/f9006acb-026d-492d-bd0d-6d382fa97e6c)


just fired up a VM and running the autoinstall
nix-shell -p git curl
sh <(curl -L https://github.com/JaKooLit/Ja-ZaneyOS/raw/ja-edited/install-zaneyos.sh)


it is running fine

**Comment by daedaevibin** [comment]
> ![image](https://github.com/user-attachments/assets/f9006acb-026d-492d-bd0d-6d382fa97e6c)
> 
> 
> just fired up a VM and running the autoinstall
> nix-shell -p git curl
> sh <(curl -L https://github.com/JaKooLit/Ja-ZaneyOS/raw/ja-edited/install-zaneyos.sh)
> 
> 
> it is running fine
> 

Not to do with your script, I was meaning nix os itself. The graphical installer wouldn't function for an unknown reason no matter what option was selected, had to go minimal.

**Comment by JaKooLit** [comment]
oh I misunderstood..

check the sha256 sum... could be bad copy of iso you have

**Comment by daedaevibin** [comment]
> oh I misunderstood..
> 
> check the sha256 sum... could be bad copy of iso you have

No, that wasn't it either. I have no idea. That's happened a lot with OSs like Nix, Garuda, Athena, and others. Very odd. Usually only occuring after installation, not before.

Anyway, the wiki stuff for this is very broad and unspecific. I'm sitting here having to figure out how to basically chroot (nixos-enter) to use nixos-rebuild properly with an internet connection because otherwise there's no interfaces for WiFi or Ethernet of absolutely any type or form.

Someone should fix that.

**Comment by daedaevibin** [comment]
> oh I misunderstood..
> 
> check the sha256 sum... could be bad copy of iso you have

Okay I'm completely stuck.

I can't rebuild

I can't log in as root

I can't log in as the added user

I can't fix this random PAM issue I'm having when trying to do absolutely anything such as sudo commands or rebuilding. I'm completely stuck and can do absolutely nothing


Finally got network manager to let me enable it. You won't believe how long this is taking to do already.


I'd like assistance in adding NixOS channel back. It suddenly vanished and using nich-channel --add doesn't do anything at all

**Comment by JaKooLit** [comment]
if you are experiencing on other distros, it could just mean a bad usb / or bad sectors on usb, or usb thumb drive failing or port failing etc....

or in general hardware failure

**Comment by daedaevibin** [comment]
> if you are experiencing on other distros, it could just mean a bad usb / or bad sectors on usb, or usb thumb drive failing or port failing etc....
> 
> or in general hardware failure
> 

No, fedora finally gave my old hardware drive the good kick it needed and it gave out previously today.

And I'm having constant issues with Ja-ZaneyOS, so I plan to replace it with NixOS-Hyprland instead.

How would I go about doing so?
